name: Publish

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-20.04
            rust_target: x86_64-unknown-linux-gnu
            ext: ''
            args: ''
          - os: ubuntu-20.04
            rust_target: aarch64-unknown-linux-gnu
            ext: ''
            args: ''
          - os: macos-latest
            rust_target: x86_64-apple-darwin
            ext: ''
            args: ''
          - os: macos-latest
            rust_target: aarch64-apple-darwin
            ext: ''
            args: ''

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Dependencies (ubuntu only)
        # if: matrix.platform == 'ubuntu-20.04'
        run: |
          echo ${{ matrix.platform }}
          # sudo apt-get update
          # sudo apt-get install -y pkg-config libglib2.0-dev libgdk-pixbuf2.0-dev libgtk-3-dev libsoup2.4-dev libjavascriptcoregtk-4.0-dev libwebkit2gtk-4.0-dev libappindicator3-dev

      - name: Setup Node Dependencies
        run: |
          cd src
          npm i
          cp -r node_modules/@tauri-apps/ lib/
          rm -rf node_modules

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: 'v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
